### ISSUE TITLE
Data writing and reading error

### ISSUE THREAD

**Issue by m273033** [createamind/candy#1]
Hey,
I am trying to run this implementation on my machine but I get the following errors each time before it starts a new episode,

**On the client side -** 
ERROR: (localhost:2002) failed to write data: [Errno 32] Broken pipe
ERROR: (localhost:2000) failed to read data: [Errno 104] Connection reset by peer

**In Carla server -** 
ERROR: tcpserver 0 : error reading message: Operation canceled
ERROR: tcpserver 0 : error writing message: Operation canceled
ERROR: tcpserver 2000 : error reading message: End of file
[2018.10.10-09.06.50:508][ 54]LogCarlaServer: Warning: Client disconnected, server needs restart

I'm just not sure if these errors are due to the server restart or this is an issue with my machine.
Thanks in advance

**Comment by zdx3578** [comment]
carla server 启动了？ 客户端服务器通信 端口一致？

**Comment by m273033** [comment]
Yes. It runs for some time and does the memory extraction part and then it just restarts and throws these exceptions. I am attaching the logs of both Carla Server and Candy Client, I have highlighted the parts of the error. When the error occurs, it restarts the pygame and Carla simulator.

[Carla Logs.pdf](https://github.com/createamind/candy/files/2468299/Carla.Logs.pdf)
[Client log.pdf](https://github.com/createamind/candy/files/2468300/Client.log.pdf)

**Comment by xjy8943** [comment]
Traceback (most recent call last):
  File "E:/桌面/github_video/candy-master/main.py", line 644, in <module>
    main()
  File "E:/桌面/github_video/candy-master/main.py", line 627, in main
    wrapper = Carla_Wrapper()
  File "E:\桌面\github_video\candy-master\carla_wrapper.py", line 27, in __init__
    self.machine = Machine()
  File "E:\桌面\github_video\candy-master\candy_model.py", line 68, in __init__
    self.ppo = PPO(args, 'ppo', z=z, test_z=test_z, ent_coef=0.00000001, vf_coef=1, max_grad_norm=0.5)
  File "E:\桌面\github_video\candy-master\modules\ppo.py", line 80, in __init__
    act_model = LstmPolicy(args, 'ppo', test_z, 1, 1, reuse=False)
  File "E:\桌面\github_video\candy-master\modules\ppo.py", line 46, in __init__
    self.pd, self.pi = self.pdtype.pdfromlatent(o)
AttributeError: 'DiagGaussianPdType' object has no attribute 'pdfromlatent'
请问找不到 pdfromlatent 怎么回事啊  用的baselines 0.1.5

**Comment by noahcao** [comment]
I'm facing the same problem. Anyone has some idea to solve it? Thx
